### ISSUE TITLE
ValueError: ./MARS/bbox_test/0002/0002C1T0012F001.jpg is not acceptable

### ISSUE THREAD

**Issue by Peanut736** [weleen/AGRL.pytorch#9]
Hi~thanks for your code first. I used trained model and pose.json you offered,  occur this problem:
Traceback (most recent call last):
  File "train_vidreid_xent_htri.py", line 604, in <module>
    main()
  File "train_vidreid_xent_htri.py", line 331, in main
    distmat = test(model, queryloader, galleryloader, args.pool, use_gpu, return_distmat=True)
  File "train_vidreid_xent_htri.py", line 504, in test
    for batch_idx, (imgs, pids, camids, adj) in enumerate(queryloader):
  File "/project/anaconda3/envs/torch171/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/project/anaconda3/envs/torch171/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/project/anaconda3/envs/torch171/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/project/anaconda3/envs/torch171/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/project/anaconda3/envs/torch171/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/project/anaconda3/envs/torch171/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/project/anaconda3/envs/torch171/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/project/vedioreid/AGRL-master/torchreid/dataset_loader.py", line 208, in __getitem__
    num_scale=self.num_scale, pyramid_part=self.pyramid_part)
  File "/project/vedioreid/AGRL-master/torchreid/dataset_loader.py", line 259, in generate_graph
    raise ValueError('{} is not acceptable'.format(path))
ValueError: /scratch/vedioreiddata/MARS/bbox_test/0002/0002C1T0012F001.jpg is not acceptable

**Comment by weleen** [comment]
hi, @Peanut736 If you find that some ids are not in your downloaded MARS dataset, I think this is caused by the difference of MARS dataset. My suggest is using AlphaPose or Openpose to generate a new pose.json.
